### ISSUE TITLE
Default Distance 150 meters does not update

### ISSUE THREAD

**Issue by wd40pyro** [modestimpala/OdinOnDemand#1]
**Issue:** Default Distance to stop listening to media isn't working.

**Reproducibility:** 100%
**Steps to reproduce:**
1) Updated Client Config File setting from 150 to 20
2) Update dedicated server Side Config File setting from 150 to 20
3) Restart server and start game
4) Boombox stays at 150m distance

**Impact:** 150 meters is too large especially if players live close to each other.

**Comment by modestimpala** [comment]
I successfully reproduced this, and am currently looking into it. Thank you!

**Comment by modestimpala** [comment]
- Fixed Boombox Default Distance
- Added separate Boombox Master Volume and Boombox Default Distance
