### ISSUE TITLE
Suggestion - link/sync players and speakers together

### ISSUE THREAD

**Issue by Dubzter** [modestimpala/OdinOnDemand#10]
Hi, I could not find where to write ir suggest this... Is there a possibility that you can link/sync players together? I would like to have speakers all over my abse since its very soft and as soon as I get away from tv I can almost not hear the music

Regards
Dubzter

**Comment by modestimpala** [comment]
Hi Dubzter,

The mod is also located on  the Nexus website, which has a nice bug tracker and comment section where you could submit things if you'd like.

https://www.nexusmods.com/valheim/mods/2229

Having speakers linked to players is a planned feature for the mod! I'm not sure when it will be added, but it is on the list.

For the time being, have you tried adjusting Screen / Boombox Default Distance in the config? Increasing this will allow you to hear the sound from media-players at a larger distance. I believe this is 50 by default, but try setting it to 100+. Give this a try and see how it works!

![image](https://user-images.githubusercontent.com/45338507/220611410-51bb7358-0137-417b-b88f-22c9cd5a1065.png)


I appreciate the suggestion, hope you're enjoying the mod.
Moddy

**Comment by Dubzter** [comment]
Thanx for getting back to me

Sounds amazing, and yes I have done that, it works, still not all over my
base, hence I suggested the speakers, but it is better, thanx for the mod
^^

I am not sure about what it should look like, but an old big screen tv(like
the large one, but themed accordingly) would be nice.
But I will have to give examples. Maybe like a wood border around it or
something.

But hey thats for another day, thanx for the awesome mod, nothing as nice
as putting some viking music on while around the base XD

Regards
Dubzter
