### ISSUE TITLE
Continuous playback

### ISSUE THREAD

**Issue by ErDuh** [modestimpala/OdinOnDemand#11]
Good morning,

First of all, congratulations for the idea, it's great to be able to use these screens on my server. It works perfectly but I have a question: would it be possible that the playback resumes when a player enters the zone? currently the link disappears when there is no one and the screens stop.

Thanks

**Comment by brianmiller** [comment]
Super cool mod.  And +1 to this.  Also when joining a server back after setting a youtube video the screen is blank, needing to re-copy/paste the youtube.

We want to have a giant screen at spawn for new players to see.  

Love the mod, truly.

**Comment by modestimpala** [comment]
Autoplay has been implemented - However, I will look into saving the Youtube link instead of the direct CDN link to possibly stop link expiration. Thanks for the feedback!
