### ISSUE TITLE
Consistent crashing 

### ISSUE THREAD

**Issue by brianmiller** [modestimpala/OdinOnDemand#13]
I have a fairly robust deployment (dockerized) of your NodeJS server running and it's working great--but the game crashes fairly consistently when enabling the mod.  Disabling it prevents crashing.

Nothing appears in the BepInEx console or server logs. Here's the bottom snippet of my client's player.log file. Could this be OOD?

Any help is appreciated. Thank you for the great work!

========== OUTPUTTING STACK TRACE ==================

0x00007FF81CBED071 (UnityPlayer) UnityMain
0x00007FF81CBE889E (UnityPlayer) UnityMain
0x00007FF81CEA686B (UnityPlayer) UnityMain
0x00007FF81CBDAF22 (UnityPlayer) UnityMain
0x00007FF81CBDEF91 (UnityPlayer) UnityMain
0x00007FF81CC0214B (UnityPlayer) UnityMain
0x00007FF81CC0202D (UnityPlayer) UnityMain
0x00007FF81C66516A (UnityPlayer) UnityMain
0x00007FF81C665210 (UnityPlayer) UnityMain
0x00007FF81C6694A8 (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF81C4269DA)
0x00007FF81C4269DA (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF81C424EAB)
0x00007FF81C424EAB (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF81C429F02)
0x00007FF81C429F02 (UnityPlayer) (function-name not available)
0x00007FF81C42B0AB (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF737CD11F2)
0x00007FF737CD11F2 (valheim) (function-name not available)
0x00007FF90EF8269D (KERNEL32) BaseThreadInitThunk
0x00007FF91000A9F8 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
Here's a screenshot from Visual Studio of the dump file
![image](https://user-images.githubusercontent.com/342276/236732253-76f8aaa1-7216-4eb0-988d-2fec61180a33.png)

**Comment by modestimpala** [comment]
Hey Brian,

Happy to hear the NodeJS Server is working well for you. I created that before working in YoutubeExplode so I'm glad to hear it's actually getting used!

As for the crashes, yes, it is related to the mod as far as I know.
I have previously received crash reports from others and investigated. I analyzed multiple crash dumps to find out the culprit is the new Valheim update to Unity version 2020.3.45. 

Here you can find the comment I left on Nexus regarding the manner:

> "I've gotten a report of some crashes recently and it appears the recent upgrade to Unity version 2020.3.45 may have [introduced a bug into the built in Unity VideoPlayer](https://forum.unity.com/threads/crash-windowsvideotextureoutput-releasedrawnsamples-bool.1396480/). If I manage to find any fix I'll be sure to push it out, but for the time being you may have crashes during video playback. There doesn't seem to be much I can do about this currently, and this may be an issue until a Unity hotfix or the Valheim developers updating the game to a newer Unity version which doesn't contain the bug. It appears it could be related to MP4 files, so we recommend utilizing VP8 codec videos or MP3/SoundCloud options as a temporary measure.
> 
> Apologies for any inconvenience."

Unfortunately I'm not currently investigating any fix since it appears this is beyond my capabilities. The issue lies within Unity's internal code and I cannot  seem to even reproduce it consistently. 

If you are able to consistently reproduce the crash and can write down steps that would be incredibly valuable. You could provide that information here or on the Unity forum link above (with logs and crash dump if possible). Otherwise I can only suggest to try and avoid MP4 files and prioritize VP8 codecs (webm) for videos.

Thanks,
Moddy

**Comment by brianmiller** [comment]
Hi Moddy, 

Thank you for the detailed reply.  I'll work on getting steps together to reproduce the issue.  

Is it possible to get local file and remote file video playback steps documented?  E.g., config settings, in-game path setting, etc...?  

We're also the developers of [PhValheim](https://github.com/brianmiller/phvalheim-server) and this system allows us to keep clients and servers in sync.  We could quite easily ensure clients have local copies (of reasonable size) of our videos, if this would mitigate this known Unity bug.

Instructions on remote play would be excellent as well.  Can we just stick a direct URL to a .webm file and it will just start playing?  That would be excellent. I suppose no transcoding :)

**Comment by modestimpala** [comment]
Always happy to help!

For local files, currently it's an absolute path lookup. You can just specify direct paths in the URL field, or add a file:// prefix.  For example, if I have a file on my desktop, I'd enter "C:\Users\Moddy\Desktop\file.mp4" - to allow multiplayer sync, each player would have to have files in an identical location.

Obviously this current approach is not great for allowing sync between local files on separate clients - ideally, we'd like to just search from a relative path around the plugin's folder so you can easily distribute video files with the mod or modpack.
I'm currently working on some potential features regarding speakers and linking devices - but on the next version, I will make it a goal to implement some sort of relative path search for local files to help mitigate the bug as you stated.
I'll most likely make it so the base relative path is the plugin's folder, then you just have your custom media files in a subdirectory, like /Bepinex/plugins/OOD/media - then in game you'd type "media/file.mp4" to play your file.

Remote play should be fairly straightforward and allow direct URL copy and pasting for all files, including .webm. 
I went ahead and tested this for you, using the big bunny blender video located here: https://github.com/benhosmer/HTML5-Test-Videos/raw/master/big_buck_bunny.webm
Pasting this URL for remote playback successfully played the file, and when I saved it and played it locally it worked as well. 

As such, I'm very happy to hear your enthusiasm for the mod and really appreciate the support and feedback. I'm looking to have the next version out soon with at least some relative path support for local playback. Additionally, I'm adding a note in my trello to update the documentation to include all this information when I have time.

Best regards,
Moddy

**Comment by modestimpala** [comment]
Implemented relative path playback in 0.9.85. Updated readme to properly document usage.

Leaving ticket open for now since the crashes are still happening.

**Comment by modestimpala** [comment]
Valheim Unity version has been Updated to 2022.3.12f. I setup a test that loops through a large playlist repeatedly to check for crashing issue. It initiated playback of 1200+ videos successfully without crashing. 

If you do encounter the same crashing issue, please feel free to re-open the issue.

Regards
Moddy
