### ISSUE TITLE
Game music still plays when in range of a media player

### ISSUE THREAD

**Issue by ZenDragonX** [modestimpala/OdinOnDemand#14]
The in game default music keeps playing on top of the media player music and sounds terrible.  Is it possible to have the in game music be muted automatically while in range of a media player?  A nice crossfade based on range would be superb :)

**Comment by modestimpala** [comment]
Implemented in 0.9.95. If there are any issues with it please open a new issue. Thanks for the suggestion!

> ## 0.9.95-beta
> - New feature: In-Game Music Audio Crossfade based on distance [See config file]


**ood.valmedia.cfg**

>  How the in-game music fades in and out. Fade: Gradually changes volume based off distance from nearest active mediaplayer. None: No change.
> Setting type: FadeType
>  Default value: Fade
>  Acceptable values: Fade, None
> Music Fade Type = Fade
> 
>  The lowest volume the music will fade to in DB. -65-80 is completely silent, 0 is neutral volume.
>  Setting type: Single
>  Default value: -60
>  Acceptable value range: From -80 to 0
> Lowest Fade Volume DB = -60
