### ISSUE TITLE
Audio bug - Radios cause master mixer volume fluctiations

### ISSUE THREAD

**Issue by smoothuk** [modestimpala/OdinOnDemand#15]
This seems to happen randomly, but sometimes when you have two media players in proximity (only one needs to be actually playing something), the audio volume of the device playing fluctuates.  Might just be coincidence but it seems to happen more often with a screen and the radio (the radio doesn't even need to be placed, just selected on the hammer).

**Comment by modestimpala** [comment]
Hey smoothuk, thanks for the report. Are you by any chance adjusting the vertical drop-off or master volume settings? My first thought was to go to my AudioFader feature and take a look at that, but the only parts of my code that should modify the mediaPlayer.audioSource is the vertical drop-off I think. So I suspect this is from the new vertical drop-off feature. 
I tried playing around with a screen and a radio and wasn't really able to reproduce this. I'd love to look into this more. Are you able to place a screen and a radio where you experience this bug, and upload the save file for me? And please let me know what your config settings are like. Much appreciated.
Thanks! Moddy

**Comment by modestimpala** [comment]
I will work on adding a little deviation to the vertical drop-off settings to see if I can help with this issue.
I had known about this issue for a little while, but the master volume slider is currently bugged and causes audio fluctuations. I opened up an issue #16 for this.

**Comment by smoothuk** [comment]
[scuffedaudio.zip](https://github.com/modestimpala/OdinOnDemand/files/14423802/scuffedaudio.zip)
Here you go.  This time it happened after messing with the master volume on the theatre screen with a radio nearby.

**Comment by modestimpala** [comment]
Thanks, I really appreciate you taking the time to upload this! I will look into it.

**Comment by modestimpala** [comment]
@smoothuk You are a GENIUS for making the connection with the radio. Like I said, I had known about a similar issue for a while but could never pinpoint what was causing it. I didn't realize it was the same issue until I opened your file and it was the specific Radio prefab. I was always looking for issues with my code, but alas, there were none! The issue lied within the asset prefab itself! 

I'll have an update out for this shortly. Thanks again!

**Comment by modestimpala** [comment]
Struggled with thunderstore for a bit but the new version is now uploaded with the fix. If you notice anything related please leave a comment, and feel free to open any future issues you have. Thanks!
