### ISSUE TITLE
Step-by-step tutorial needed for Youtube Setup

### ISSUE THREAD

**Issue by wd40pyro** [modestimpala/OdinOnDemand#2]
This is more of a request. The current instructions are great for setting up Youtube, but I am lost at start.sh and server.js files. An end-to-end step by step video tutorial will really help adoption and admins launch this mod on servers! 

Thank you :)!

**Comment by modestimpala** [comment]
Hello,

I have just uploaded a tutorial on the Youtube set up here: https://www.youtube.com/watch?v=9_vs8MItO38

I am also happy to say that I am close to having an alternative out for this setup on the next version.

Thanks for the request!
