### ISSUE TITLE
Can't place workbench (or anything else)

### ISSUE THREAD

**Issue by Codeynn** [modestimpala/OdinOnDemand#24]
Hello, today I wanted to install this mod on my dedicated server. After installing I noticed I cannot place a workbench, it spits out an error in client's console:

```
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'assembly_steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::PlacePiece>(Player,Piece)
Player.UpdatePlacement (System.Boolean takeInput, System.Single dt) (at <da52c09f594f4a7480000b7420815ba7>:0)
Player.Update () (at <da52c09f594f4a7480000b7420815ba7>:0)
```

I tried in also in singleplayer, same issue. Also tried to delete all the mods and keep just this one + OODLib, same issue. Deleting the mod ofcourse fixed the issue.

Any possible solution please?

**Comment by modestimpala** [comment]
Hi Codeynn,

Valheim was updated yesterday. Please update to the newest version of the plugin (1.0.5) on Thunderstore or Nexus to resolve this issue.

Thanks
Moddy
